# Generated by Django 5.2.17 on 2026-09-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='druginteraction',
            index=models.Index(fields=['drug_a', 'drug_b'], name='drug_checke_drug_a_eba107_idx'),
        ),
        migrations.AddIndex(
            model_name='druginteraction',
            index=models.Index(fields=['drug_a'], name='drug_checke_drug_a_405887_idx'),
        ),
        migrations.AddIndex(
            model_name='druginteraction',
            index=models.Index(fields=['drug_b'], name='drug_checke_drug_b_758db5_idx'),
        ),
    ]
